<a href="https://colab.research.google.com/github/Syeda-Eman/40_days_of_Python/blob/main/Day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Library**

In [1]:
#importing numpy
import numpy as np

In [2]:
#creating array using numpy
food = np.array(['Burger','Pizza','Pasta'])
food

array(['Burger', 'Pizza', 'Pasta'], dtype='<U6')

In [3]:
#creating array using numpy
price = np.array([5,10,7])
price

array([ 5, 10,  7])

In [4]:
#checking type
type(price)

numpy.ndarray

In [5]:
#checking type
type(food)

numpy.ndarray

In [6]:
#checking length
len(food)

3

In [7]:
#checking length
price[2]

7

In [8]:
#array
price[0:]

array([ 5, 10,  7])

In [9]:
#printing second element of the array
food[1]

'Pizza'

In [10]:
#checking mean
price.mean()

7.333333333333333

In [11]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [14]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#specify
np.arange (2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
#specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
#table of 5 using specific interval
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
#line space
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [19]:
#specify datatype
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [20]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# **Array functions**

In [21]:
#creating array
a = np.array([10,12,15,2,4,6,8])
a

array([10, 12, 15,  2,  4,  6,  8])

In [22]:
#ordering array
a.sort()
a

array([ 2,  4,  6,  8, 10, 12, 15])

In [23]:
b = np.array([10.2,3.4,56.8,9.6,45.5])
b

array([10.2,  3.4, 56.8,  9.6, 45.5])

# **2-D arrays**

In [24]:
x=np.array([[1,2,3],[5,4,3]])
x

array([[1, 2, 3],
       [5, 4, 3]])

In [25]:
y=np.array([[3,9,5],[6,4,8]])
y

array([[3, 9, 5],
       [6, 4, 8]])

In [26]:
np.concatenate((x,y),axis=1)

array([[1, 2, 3, 3, 9, 5],
       [5, 4, 3, 6, 4, 8]])

In [34]:
a = np.array([[[0,1,2,3],
                       [4,5,6,7]],

                      [[0,1,2,3],
                       [4,5,6,7]],

                      [[0,1,2,3],
                       [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [32]:
#to find the num of dimensions
a.ndim

3

In [36]:
b = np.array([[5,6,7],
              [8,9,10],
              [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [37]:
b.ndim

2

In [38]:
#to find size or number of elements
a.size

24

In [39]:
#shape
a.shape

(3, 2, 4)

In [41]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
#reshape
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
#reshape
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [46]:
#convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a.shape

(9,)

In [48]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
b.shape

(1, 9)

In [50]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a[2:6]

array([3, 4, 5, 6])

In [53]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [54]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
a.sum()

45

In [56]:
a.mean()

5.0