<a href="https://colab.research.google.com/github/Syeda-Eman/40_days_of_Python/blob/main/Day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Library**

In [1]:
#importing numpy
import numpy as np

In [2]:
#creating array using numpy
food = np.array(['Burger','Pizza','Pasta'])
food

array(['Burger', 'Pizza', 'Pasta'], dtype='<U6')

In [3]:
#creating array using numpy
price = np.array([5,10,7])
price

array([ 5, 10,  7])

In [4]:
#checking type
type(price)

numpy.ndarray

In [5]:
#checking type
type(food)

numpy.ndarray

In [6]:
#checking length
len(food)

3

In [7]:
#checking length
price[2]

7

In [8]:
#array
price[0:]

array([ 5, 10,  7])

In [9]:
#printing second element of the array
food[1]

'Pizza'

In [12]:
#checking mean
price.mean()

7.333333333333333

In [13]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
#empty
np.empty(5)

array([0., 0., 0., 0., 0.])

In [17]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#specify
np.arange (2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
#specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#table of 5 using specific interval
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
#line space
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [25]:
#specify datatype
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [26]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# **Array functions**

In [29]:
#creating array
a = np.array([10,12,15,2,4,6,8])
a

array([10, 12, 15,  2,  4,  6,  8])

In [31]:
#ordering array
a.sort()
a

array([ 2,  4,  6,  8, 10, 12, 15])

In [34]:
b = np.array([10.2,3.4,56.8,9.6,45.5])
b

array([10.2,  3.4, 56.8,  9.6, 45.5])

# **2-D arrays**

In [44]:
x=np.array([[1,2,3],[5,4,3]])
x

array([[1, 2, 3],
       [5, 4, 3]])

In [45]:
y=np.array([[3,9,5],[6,4,8]])
y

array([[3, 9, 5],
       [6, 4, 8]])

In [46]:
np.concatenate((x,y),axis=1)

array([[1, 2, 3, 3, 9, 5],
       [5, 4, 3, 6, 4, 8]])