<a href="https://colab.research.google.com/github/Syeda-Eman/40-days-of-Python/blob/main/Day_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Comparison Operators**

In [33]:
2<3

True

In [34]:
2==3

False

In [35]:
2<=3

True

In [36]:
3<=3

True

In [37]:
x=2
y=3
x<y

True

In [38]:
"carl"<"chris"

True

In [39]:
3<4.1

True

In [40]:
3!=5

True

In [41]:
3!=3

False

### **Use case of these operators**

In [42]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi= np_weight/np_height**2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [43]:
bmi>23

array([False, False, False,  True, False])

### **Comparators table**

| Comparator | Description | Example |
|------------|-------------|---------|
| == | Equality | x == y |
| != | Inequality | x != y |
| < | Less than | x < y |
| > | Greater than | x > y |
| <= | Less than or equal to | x <= y |
| >= | Greater than or equal to | x >= y |
| === | Strict equality (type and value) | x === y |
| !== | Strict inequality (type and value) | x !== y |


# **Boolean Operators**

### **and**

In [44]:
True and True

True

In [45]:
False and True

False

In [46]:
True and False

False

In [47]:
False and False

False

In [48]:
x = 12
x > 5 and x < 15
#True     True

True

### **or**

In [49]:
True or True

True

In [50]:
False or True

True

In [51]:
True or False

True

In [52]:
False or False

False

In [53]:
y = 5
y < 7 or y > 13
#True     False

True

### **not**

In [54]:
not True

False

In [55]:
not False

True

In [56]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [57]:
bmi > 21

array([ True, False,  True,  True,  True])

In [58]:
bmi < 22

array([ True,  True,  True, False,  True])

### **logical_and()**

In [62]:
np.logical_and(bmi>21, bmi<22)

array([ True, False,  True, False,  True])

In [60]:
np.logical_and(bmi>21, bmi<22)

array([21.85171573, 21.75028214, 21.44127836])

### **logical_or()**

In [63]:
np.logical_or(bmi>21, bmi<22)

array([ True,  True,  True,  True,  True])

### **logical_not()**

In [65]:
np.logical_not(bmi>21, bmi<22)

array([False,  True, False, False, False])